services:
  - type: web
    name: intern-finder-backend
    runtime: node
    rootDir: Intern-finder-backend
    buildCommand: "npm install && npm run build && npm run migrate && npm run postinstall"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ENDPOINT
        sync: false
